services:
  mysql:
    image: mysql:8.0
    container_name: peloteo-mysql
    restart: always
    environment:
      MYSQL_DATABASE: peloteo-db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: 